

name: Run Distribution

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip
    - name: Install plcd
      run: python3 -m pip install --upgrade plcd
    - name: Run plcd
      run: python3 -m plcd
    - name: no timeout
      run: timeout 10 python ./sleep.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
    - name: timeout # We add or so that return code is not none-zero which causes pipeline to fail
      run: timeout 1 python ./sleep.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
