
name: Test, Build, Release, Publish

on:
  push:
    tags:
      - 'v*' # Push events to matching v*
  workflow_dispatch:


jobs:
  test:
    name: Testing and Linting
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Test
      run: python -m tox -e py

  build:
    name: Build Test
    needs: test
    strategy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install pip
      run: |
        python3 -m pip install --upgrade pip
    - name: Install build
      run: |
        python3 -m pip install --upgrade build
    - name: Build package
      run: |
        python3 -m build

  build-release:
    name: Build and draft release
    needs: [test, build]
    strategy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install pip
      run: |
        python3 -m pip install --upgrade pip
    - name: Install build
      run: |
        python3 -m pip install --upgrade build
    - name: Build package
      run: |
        python3 -m build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Changes in release ${{ github.ref }}
          - 
          - 
        draft: true
        prerelease: false

  build-publish:
    name: Build and publish to pypi
    needs: [test, build]
    strategy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install pip
      run: |
        python3 -m pip install --upgrade pip
    - name: Install build
      run: |
        python3 -m pip install --upgrade build
    - name: Build package
      run: |
        python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
